name: Build iOS for AltStore (Olajfolt)

on:
  workflow_dispatch:   # kézzel indítható build
  push:
    branches: [ main ] # vagy automatikusan fut minden push után

jobs:
  build_ios:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4

      - name: Use Xcode 16
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.4'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.1'  # használt Flutter verziód

      - name: Check Flutter
        run: flutter --version

      - name: Get dependencies
        run: flutter pub get

      - name: Build unsigned iOS IPA
        run: flutter build ipa --release --no-codesign

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: Olajfolt-IPA
          path: build/ios/ipa/*.ipa
