name: Build iOS for AltStore (Olajfolt)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_ios:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4

      - name: Use Xcode 16
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.4'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.1'

      - name: Check Flutter
        run: flutter --version

      - name: Get dependencies
        run: flutter pub get

      - name: Build unsigned iOS app
        run: flutter build ios --release --no-codesign
        
      - name: Create Payload folder and IPA
        run: |
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r Olajfolt.ipa Payload/
          
      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: Olajfolt-IPA
          path: Olajfolt.ipa
